#!/usr/bin/env python3

import csv
from json import dumps
import sys

def main(argv):
    if len(argv) == 0:
        raise Exception("Filename is missing.")

    row_length = int(argv[1]) if len(argv) >= 2 and argv[1].isdigit() else 5

    data = []

    with open(argv[0]) as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=',', quotechar='"')
        for row in csv_reader:
            if all(x is None for x in row):
                break

            if len(row) < row_length:
                break

            data.append(row[0:row_length])
        
    if len(argv) >= 3 and argv[2]=='pretty':
        print(dumps(data[1:], sort_keys=True, indent=4, separators=(',', ': ')))
    else:
        print(dumps(data[1:]))

if __name__ == "__main__":
    main(sys.argv[1:])

