#!/usr/bin/env python3

from ezodf import opendoc
from json import dumps
import sys

COLS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

def get_cell_name(x, y):
    return "%s%d" % (COLS[x], y+1)

def get_cell_value(sheet, x, y):
    cell_name = get_cell_name(x, y)
    cell = sheet[cell_name]

    return str(cell.value) if cell else ""

def main(argv):
    if len(argv) == 0:
        raise Exception("Filename is missing.")

    doc = opendoc(argv[0])
    sheet = doc.sheets[0]

    row_length = int(argv[1]) if len(argv) >= 2 and argv[1].isdigit() else 5

    if row_length > len(COLS) or row_length > sheet.ncols():
        raise Exception("Column was unexpected: %s" % x)

    data = []

    for y in range(1, sheet.nrows()):
        row = [get_cell_value(sheet, x, y) for x in range(0, row_length)]

        if all(x is "" for x in row):
            break

        data.append(row)

    if len(argv) >= 3 and argv[2]=='pretty':
        print(dumps(data, sort_keys=True, indent=4, separators=(',', ': ')))
    else:
        print(dumps(data))

if __name__ == "__main__":
    main(sys.argv[1:])

