#!/usr/bin/env python3

from openpyxl import load_workbook
from json import dumps
import sys

def main(argv):
    if len(argv) == 0:
        raise Exception("Filename is missing.")

    doc = load_workbook(filename=argv[0], read_only=True)
    sheet = doc.active

    row_length = int(argv[1]) if len(argv) >= 2 and argv[1].isdigit() else 4

    data = []

    for row in sheet.iter_rows():
        if all(x.value is None for x in row):
            break

        if len(row) < row_length:
            break

        data.append([cell.value if cell.value else "" for cell in row[0:row_length]])

    if len(argv) >= 3 and argv[2]=='pretty':
        print(dumps(data[1:], sort_keys=True, indent=4, separators=(',', ': ')))
    else:
        print(dumps(data[1:]))

if __name__ == "__main__":
    main(sys.argv[1:])

