#!/usr/bin/env python3

import http.server
import socketserver
import argparse
from klein import run, route

parser = argparse.ArgumentParser()

parser.add_argument("-p", "--port", help="Port", type=int)

args = parser.parse_args()

print("serving at port", args.port)

@route('/')
def home(request):
    return "Hello, world!\n"

run("localhost", args.port)

