FROM peteraba/d5-python

COPY bin/csv /usr/bin/
COPY bin/xlsx /usr/bin/
COPY bin/ods /usr/bin/
COPY bin/spreadsheet /usr/bin/
COPY bin/parser /usr/bin/
COPY bin/persister /usr/bin/
COPY bin/finder /usr/bin/
COPY bin/scorer /usr/bin/
COPY bin/router /usr/bin/
COPY bin/admin /usr/bin/
COPY bin/derdiedas /usr/bin/
COPY bin/conjugate /usr/bin/

EXPOSE 10100
EXPOSE 10110
EXPOSE 10120
EXPOSE 10210
EXPOSE 10220
EXPOSE 10220
EXPOSE 10310
EXPOSE 10320
EXPOSE 10410

