FROM peteraba/d5-python

COPY csv /usr/bin/
COPY xlsx /usr/bin/
COPY ods /usr/bin/
COPY spreadsheet /usr/bin/
COPY parser /usr/bin/
COPY persister /usr/bin/
COPY finder /usr/bin/
COPY scorer /usr/bin/
COPY router /usr/bin/
COPY admin /usr/bin/
COPY derdiedas /usr/bin/
COPY conjugate /usr/bin/

EXPOSE 10100
EXPOSE 10110
EXPOSE 10120
EXPOSE 10210
EXPOSE 10220
EXPOSE 10220
EXPOSE 10310
EXPOSE 10320
EXPOSE 10410

