#!/usr/bin/env python3

from openpyxl import load_workbook
from json import dumps
import sys
import datetime

def main(argv):
    if len(argv) == 0:
        raise Exception("Filename is missing.")

    doc = load_workbook(filename=argv[0], read_only=True)
    sheet = doc.active

    row_length = int(argv[1]) if len(argv) >= 2 and argv[1].isdigit() else 6

    data = []

    day0 = datetime.date.fromtimestamp(0)

    for row in sheet.iter_rows():
        if all(x.value is None for x in row):
            break

        if len(row) < row_length:
            break

        row_data = [cell.value if cell.value else "" for cell in row[0:row_length]]

        if row[5].value != "date":
            date = day0 + datetime.timedelta(round(float(row[5].value)) - 25569)
            row_data[5] = date.strftime("%Y-%m-%d")

        if row[6].value != "score":
            row_data[6] = str(int(row_data[6]))

        data.append(row_data)

    if len(argv) >= 3 and argv[2]=='pretty':
        print(dumps(data[1:], sort_keys=True, indent=4, separators=(',', ': ')))
    else:
        print(dumps(data[1:]))

if __name__ == "__main__":
    main(sys.argv[1:])

